export const SET_LOCATION = 'SET_LOCATION';
export const SET_CUSTOM_LOCATION = 'SET_CUSTOM_LOCATION';
export const SET_WEATHER_DATA = 'SET_WEATHER_DATA';
export const SET_CUSTOM_WEATHER_DATA = 'SET_CUSTOM_WEATHER_DATA';
